name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: yarn install

      - run: yarn lint